### ISSUE TITLE
Add credit to Bottfy in the README and the source code.

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/ladybug-geometry-polyskel#2]
Original code from here: https://github.com/Botffy/polyskel/blob/master/polyskel.py

@mostaphaRoudsari @chriswmackey is there any particular format for crediting the original author? I was thinking of just mentioning code was revised from him and using Chicago citation style to reference his repo.  Also I think it would be good to send him an email to request his real name so we can credit him appropriately.

**Comment by mostaphaRoudsari** [comment]
Yes. Let's get in touch and ask about the best approach to reference his work. Thanks.

**Comment by TuomLarsen** [comment]
It is very relevant!

You stole Botffy's code (yes, stole, because his code is licensed under LGPL 3.0 and you simply took it and remove the whole copyright and now pretend you wrote it yourself) and you "were thinking of just mentioning code was revised from him"?

While you are "looking for a replacement" (almost half a year later), show some basic decency and add him as the author.

**Comment by mostaphaRoudsari** [comment]
Hi @TuomLarsen,

Thank you for the note. You might be overreacting here. If we wanted to still the code we wouldn't open an issue here to make sure we give him credit.

I believe the reason that @saeranv mentioned it is not relevant is that we decided not to use the code at that point. But then we didn't and you are right. We should have.

I'm re-opening this issue so we add credits as needed. Thanks again!

**Comment by chriswmackey** [comment]
Thanks for bringing this to our attention, @TuomLarsen . You are right that we should be doing a better job crediting Botffy and we shouldn't have closed this issue while we were still figuring out how to construct this package. Now that the package is stable and we can confidently say that it's a derivative work of Botffy's code, I have added a credits section to our Readme clarifying that it's a derivative work and the key things that we changed:
https://github.com/ladybug-tools/ladybug-geometry-polyskel#readme

You'll see that the credit also appears in the PyPI page as well:
https://pypi.org/project/ladybug-geometry-polyskel/

From [the message that appears at the top of the GNU licenses](https://github.com/ladybug-tools/ladybug-geometry-polyskel/blob/master/LICENSE#L5-L6), I don't think we are supposed to modify it to add a copyright for ourselves or Botffy ([Bottfy hasn't done this with his own license](https://github.com/Botffy/polyskel/blob/master/LICENSE#L4-L6)) but I added a copyright to the ReadMe and PyPI that mentions both of us.

I'm also adding credit at the location on our UI where we make use of Bottfy's code:
https://github.com/ladybug-tools/dragonfly-grasshopper/pull/195

If there is any other place where we should credit Botffy that we are missing, just let us know and we'll be happy to do so. We are thankful for the starting point that the polyskel package gave us and Bottfy definitely deserves credit.

**Comment by TuomLarsen** [comment]
Thank you for resolving the issue so promptly.

**Comment by chriswmackey** [comment]
Glad to hear it, @TuomLarsen . I am going to close out this issue for now, then. If we find any other place where we should add a credit for Botffy, just let us know here and we can re-open it.

**Comment by saeranv** [comment]
Yes, this is my fault for not following up and re-opening this once it was clear the code was going to be used for a while. Definitely Botffy deserves credit and it was not my intention to try and hide that in anyway. Thanks for resolving it.
