### ISSUE TITLE
'Vector2D' object has no attribute 'is_equivalent'

### ISSUE THREAD

**Issue by oricou** [ladybug-tools/ladybug-geometry-polyskel#209]
Hi,

 ```
poly = [[129.70397169083816, 71.71159319019317], [129.9979717140897, 41.97243094226565], [92.21932907858722, 28.335609750318383], [68.00085209387457, 51.51130866701369], [68.52053881890768, 69.69522314783094], [129.70397169083816, 71.71159319019317]]
polyskel.skeleton_as_edge_list(edges, tol=0.1)
```

leads to

```
...
 File "/home/.../lib/python3.9/site-packages/ladybug_geometry_polyskel/polyskel.py", line 714, in _normalize_contour
    normed_prev.is_equivalent(normed_next, tol):
AttributeError: 'Vector2D' object has no attribute 'is_equivalent'
```

Olivier.

ps: it works with  [[0,0], [1,0], [1,1], [0,1]]

**Comment by chriswmackey** [comment]
@oricou ,

This is happening because you are not supposed to pass a duplicate vertex into that function. You should remove either the first or last vertex in your list there.

**Comment by chriswmackey** [comment]
I also did a small refactor of `ladybug_geometry` so that people won't get this error anymore:
https://github.com/ladybug-tools/ladybug-geometry/pull/304

But my original suggestion to remove duplicate vertices still holds, @oricou .
